### ISSUE TITLE
Timer devices are ignored

### ISSUE THREAD

**Issue by amirgon** [wgoossens/sopc2dts#11]
Hi,

Timer devices are defined in the sopc file:
```
   <memoryBlock>
    <isBridge>false</isBridge>
    <moduleName>timer_0</moduleName>
    <slaveName>s1</slaveName>
    <name>timer_0.s1</name>
    <baseAddress>3932160</baseAddress>
    <span>64</span>
   </memoryBlock>
```

They are even visible on the GUI:

![image](https://user-images.githubusercontent.com/11742638/146029104-7466bc24-a96a-4014-8b7b-5d73dade15e8.png)

But when running:
```
java -jar sopc2dts/sopc2dts.jar -i ip_wrap.sopcinfo --bridge-removal all --type dts
```

Timers are missing from the DTS file.

Any idea?

**Comment by wgoossens** [comment]
Hi Amirgon,
It's been a while since I've done anything on this....
Could you share your sopcinfo file and boardfiles (if any) so I can test?

**Comment by amirgon** [comment]
Hi @wgoossens 

I cannot share the sopcinfo , but I found out that a few bridge classes were missing.
When adding them in the boards XML file I can see timers now.  
I've added the bridges to `sopc_components_altera.xml`, would you like me to open a PR?

One thing I'm not sure about (unrelated to Timer devices) is how to add an `altera_vic` device class. I didn't find a VIC device type in sopc2dts.

**Comment by wgoossens** [comment]
Hi Amirgon,

a pull-request is very welcome.
WRT the VIC thinghy: It would be nice if Intel would take a lead on this but you can basically add anything through the board/component files, sopc2dts does not really put any constraints on the classes.
