### ISSUE TITLE
Issues generating DTS for arria10 Soc

### ISSUE THREAD

**Issue by dan-42** [wgoossens/sopc2dts#5]
Hi

i'm working at getting an arria10 board up and running and we hit some minor issues,
 which might be related to your tool. If the issues are related to the ``` *.socpinfo```-files and I just don't see it, please point it out.

For the arria10 to have dual-core arm activate both CPUS, I need to add ``` enable-method = "altr,socfpga-a10-smp"; ```  to the ``` cpus ``` just below ``` #size-cells = <0x0>; ```
But I m not able to do that within the ``` *.socpinfo```-file, as this is only adds stuff to the global scope.

What is generated: 
```
cpus {
    #address-cells = <0x1>;
    #size-cells = <0x0>;

    cpu@0 {
        device_type = "cpu";
        compatible = "arm,cortex-a9-17.1", "arm,cortex-a9";
        reg = <0x0>;
    };

    cpu@1 {
        device_type = "cpu";
        compatible = "arm,cortex-a9-17.1", "arm,cortex-a9";
        reg = <0x1>;
    };
};
```

what is needed
```
cpus {
    #address-cells = <0x1>;
    #size-cells = <0x0>;		
    enable-method = "altr,socfpga-a10-smp";

    cpu@0 {
        device_type = "cpu";
        compatible = "arm,cortex-a9-17.1", "arm,cortex-a9";
        reg = <0x0>;			
    };

    cpu@1 {
        device_type = "cpu";
        compatible = "arm,cortex-a9-17.1", "arm,cortex-a9";
        reg = <0x1>;			
    };
};

```

Another issue is when generating a DTS the label ``` &hps_fpga_interfaces ``` is used but nowhere defined and I cannot compile the DTS with a standard ``` dtc ```-compiler
When generating a DTB it works fine.

What is generated in the DTS:

```

hps_bridges: bridge@c0000000 {
    compatible = "altr,bridge-17.1", "simple-bus";
    reg = <0xc0000000 0x20000000>,
            <0xff200000 0x00200000>;
    reg-names = "axi_h2f", "axi_h2f_lw";
    clocks = <&hps_fpga_interfaces 0 &hps_fpga_interfaces 0>;
    clock-names = "h2f_axi_clock", "h2f_lw_axi_clock";
    #address-cells = <2>;
    #size-cells = <1>;
    ranges = <0x00000001 0x00000000 0xff200000 0x00000008>,
            <0x00000001 0x00000020 0xff200020 0x00000020>;

    sysid_qsys_0: sysid@100000000 {
        compatible = "altr,sysid-17.1", "altr,sysid-1.0";
        reg = <0x00000001 0x00000000 0x00000008>;
        clocks = <&hps_fpga_interfaces 0>;
        id = <0>;	/* embeddedsw.dts.params.id type NUMBER */
        timestamp = <1516089082>;	/* embeddedsw.dts.params.timestamp type NUMBER */
    }; //end sysid@100000000 (sysid_qsys_0)

    pio_nios_control: gpio@100000020 {
        compatible = "altr,pio-17.1", "altr,pio-1.0";
        reg = <0x00000001 0x00000020 0x00000020>;
        clocks = <&hps_fpga_interfaces 0>;
        altr,gpio-bank-width = <2>;	/* embeddedsw.dts.params.altr,gpio-bank-width type NUMBER */
        resetvalue = <0>;	/* embeddedsw.dts.params.resetvalue type NUMBER */
        #gpio-cells = <2>;
        gpio-controller;
    }; //end gpio@100000020 (pio_nios_control)
}; //end bridge@c0000000 (hps_bridges)
```

When generating a DTB and the decompile it with dtc The following is generated:

```
bridge@c0000000 {
    compatible = "altr,bridge-17.1", "simple-bus";
    reg = <0xc0000000 0x20000000 0xff200000 0x200000>;
    reg-names = "axi_h2f", "axi_h2f_lw";
    clocks = <0x0 0x0 0x0 0x0>;
    clock-names = "h2f_axi_clock", "h2f_lw_axi_clock";
    #address-cells = <0x2>;
    #size-cells = <0x1>;
    ranges = <0x1 0x0 0xff200000 0x8 0x1 0x20 0xff200020 0x20>;

    sysid@100000000 {
        compatible = "altr,sysid-17.1", "altr,sysid-1.0";
        reg = <0x1 0x0 0x8>;
        clocks = <0x0 0x0>;
        id = <0x0>;
        timestamp = <0x5a5daefa>;
    };

    gpio@100000020 {
        compatible = "altr,pio-17.1", "altr,pio-1.0";
        reg = <0x1 0x20 0x20>;
        clocks = <0x0 0x0>;
        altr,gpio-bank-width = <0x2>;
        resetvalue = <0x0>;
        #gpio-cells = <0x2>;
        gpio-controller;
    };
};

```

Thank you for your answer and let me know if you need more information.

Cheers dan

**Comment by wgoossens** [comment]
Hi dan-42,

regarding your first issue, have you tried adding
<DTAppend name="enable-method" type="string" parentlabel="cpus" val="altr,socfpga-smp"/>
to your boardinfo file?

**Comment by dan-42** [comment]
Hello @wgoossens thx for answering
yes I have tried that see 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<BoardInfo pov="hps_arm_a9_0">
<DTAppend name="enable-method" type="string" parentlabel="cpus" val="altr,socfpga-a10-smp"/>
<DTAppend name="compatible" type="string" val="altr,socfpga-arria10" action="replace"/>
[...]
</BoardInfo>
```

but the output says
```
...
DTAppend: Unable to find parent, null, for enable-method. Adding to root
...
```

And the output is the one above.
Maybe I do use the wrong *parentlabel*?

Thank you very much for helping out

Dan

**Comment by wgoossens** [comment]
Hi dan-42,

can you mail me your sopcinfo + boardinfo files? That would be the fastest way to solve this.

Walter

**Comment by dan-42** [comment]
mail is out

**Comment by dan-42** [comment]
@wgoossens any progress? any think I can help you with?
thx
dan

**Comment by wgoossens** [comment]
Hi @dan-42 ,

sorry for not replying earlier, both files you sent me were having an .sopcinfo extension so I thought the boardinfo files would come later... Actually opening the files showed me you _did_ include them...
Anyways... on to the problem at hand.
The reason the 'parentlabel' thingy doesn't work is because the cpus node does not have a label, just a node name. Luckiliy you can also specify a direct path to the node using 'parentpath' so if you change it to:

`<DTAppend name="enable-method" type="string" parentpath="/cpus" val="altr,socfpga-a10-smp"/>
`
Everything should work as expected.

Regarding your other issue: I don't get any references to hps_fpga_interfaces in the files you supplied me. Is that still an issue?

Walter

**Comment by dan-42** [comment]
Good morning @wgoossens 

Thx that helps a lot, and sry I must have missed the *parentpath* in the documentation

Concerning the other issue, this happens wen generating the dts with the following command
```sh 
sopc2dts -i ${INPUT_SOPCINFO_FILE}  -o ${OUTPUT_DTS} -t dts  --board ${BSP_SOPCINFO_FILE} --clocks --sopc-parameters all --bridge-removal all
```

I do need the ``` --clocks ``` otherwise the linux stops booting at ```  Waiting for root device /dev/mmcblk0p3... ```

And when I omit the ``` --sopc-parameters all ``` the kernel does not boot at all.

For now I can live with generating the dtb directly but, I would like to automate the generation of the dts, then copy it into yocto/meta-layer, so that I do not have any other special handling inside yocto.

Thank you again for your help,
I really appreciate it

dan
